language: c
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
addons:
  homebrew:
    packages:
      - libtommath
    update: true
jobs:
  include:
# Testing on Mac, various styles
    - name: "macOS/Xcode 11.5/Shared"
      os: osx
      osx_image: xcode11.5
      env:
        - BUILD_DIR=macosx
      install: []
      script: &mactest
        - make -C macosx
        - make -C macosx test
    - name: "macOS/Xcode 11/Shared"
      os: osx
      osx_image: xcode11
      env:
        - BUILD_DIR=macosx
      install: []
      script: *mactest
    - name: "macOS/Xcode 10/Shared"
      os: osx
      osx_image: xcode10.3
      env:
        - BUILD_DIR=macosx
      install: []
      script: *mactest
    - name: "macOS/Xcode 9/Shared"
      os: osx
      osx_image: xcode9.2
      env:
        - BUILD_DIR=macosx
      install: []
      script: *mactest
    - name: "macOS/Xcode 8/Shared"
      os: osx
      osx_image: xcode8.3
      env:
        - BUILD_DIR=macosx
      install: []
      script: *mactest
before_install:
#  - cd ${BUILD_DIR}
install:
#  - mkdir "$HOME/install dir"
#  - ./configure ${CFGOPT} "--prefix=$HOME/install dir" || (cat config.log && exit 1)
before_script:
  - export ERROR_ON_FAILURES=1
script:
#  - make
#  - make test
#  - make install
