sudo: false
language: c
jobs:
  include:
# Testing on Mac, various styles
    - name: "macOS/Xcode 11.5/Shared"
      os: osx
      osx_image: xcode11.5
      env:
        - BUILD_DIR=macosx
      before_install: &libtommath
        - cd ${BUILD_DIR}
        - git clone https://github.com/libtom/libtommath.git
        - cd libtommath
        - make
        - make install
        - cd ..
      install: []
      script: &mactest
        - make all
        # The styles=develop avoids some weird problems on OSX
        - make test styles=develop
    - name: "macOS/Xcode 11.5/Shared/Unix-like"
      os: osx
      osx_image: xcode11.5
      env:
        - BUILD_DIR=unix
# Older MacOS versions
    - name: "macOS/Xcode 11/Shared"
      os: osx
      osx_image: xcode11
      env:
        - BUILD_DIR=macosx
      before_install: *libtommath
      install: []
      script: *mactest
    - name: "macOS/Xcode 10/Shared"
      os: osx
      osx_image: xcode10.3
      env:
        - BUILD_DIR=macosx
      before_install: *libtommath
      install: []
      script: *mactest
    - name: "macOS/Xcode 9/Shared"
      os: osx
      osx_image: xcode9.2
      env:
        - BUILD_DIR=macosx
      before_install: *libtommath
      install: []
      script: *mactest
    - name: "macOS/Xcode 8/Shared"
      os: osx
      osx_image: xcode8.3
      env:
        - BUILD_DIR=macosx
      before_install: *libtommath
      install: []
      script: *mactest
install:
  - mkdir "$HOME/install dir"
  - ./configure ${CFGOPT} "--prefix=$HOME/install dir" || (cat config.log && exit 1)
before_script:
  - export ERROR_ON_FAILURES=1
script:
  - make all tcltest
  - make test
  - make install
