language: c
os: osx
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
addons:
  homebrew:
    packages:
      - libtommath
    update: true

jobs:
  include:
    - name: "macOS/Xcode 11.5/Shared"
      osx_image: xcode11.5
      install: []
      script: &mactest
        - cd macosx
        - make
        # The styles=develop avoids some weird problems on OSX
        - make test styles=develop
	- cd ..

# Older MacOS versions

   - name: "macOS/Xcode 11/Shared"
      osx_image: xcode11
      install: []
      script: *mactest

   - name: "macOS/Xcode 10/Shared"
      osx_image: xcode10.3
      install: []
      script: *mactest

   - name: "macOS/Xcode 9/Shared"
      osx_image: xcode9.2
      install: []
      script: *mactest

   - name: "macOS/Xcode 8/Shared"
      osx_image: xcode8.3
      install: []
      script: *mactest

before_install:

install:

before_script:
  - export ERROR_ON_FAILURES=1


